-- Migration script to update supabase_schema.sql to supabase_schema_updated.sql
-- This script adds new tables and updates existing ones

-- ===== CREATE NEW ENUM TYPES =====
DROP TYPE IF EXISTS venue_contact_type CASCADE;
CREATE TYPE venue_contact_type AS ENUM ('Email', 'Phone');
DROP TYPE IF EXISTS door_type_enum CASCADE;
CREATE TYPE door_type_enum AS ENUM ('Single', 'Double');
DROP TYPE IF EXISTS door_corner_enum CASCADE;
CREATE TYPE door_corner_enum AS ENUM ('Left', 'Right', 'Center');
DROP TYPE IF EXISTS door_swing_enum CASCADE;
CREATE TYPE door_swing_enum AS ENUM ('Inward', 'Outward');
DROP TYPE IF EXISTS door_hinge_enum CASCADE;
CREATE TYPE door_hinge_enum AS ENUM ('Left', 'Right');
DROP TYPE IF EXISTS rate_type_enum CASCADE;
CREATE TYPE rate_type_enum AS ENUM ('Hourly', 'Daily');
DROP TYPE IF EXISTS seasonal_rate_type_enum CASCADE;
CREATE TYPE seasonal_rate_type_enum AS ENUM ('Hourly', 'Daily', 'Package', 'All');
DROP TYPE IF EXISTS modifier_type_enum CASCADE;
CREATE TYPE modifier_type_enum AS ENUM ('Fixed', 'Percentage');
DROP TYPE IF EXISTS price_type_enum CASCADE;
CREATE TYPE price_type_enum AS ENUM ('fixed', 'per_pax');

-- ===== UPDATE EXISTING TABLES =====

-- 1. Add missing columns to user_photos
ALTER TABLE user_photos 
ADD COLUMN IF NOT EXISTS profile_photo VARCHAR(500),
ADD COLUMN IF NOT EXISTS is_primary BOOLEAN DEFAULT FALSE;

-- Add missing trigger for user_photos if not already present
DROP TRIGGER IF EXISTS update_user_photos_updated_at ON user_photos;
CREATE TRIGGER update_user_photos_updated_at
BEFORE UPDATE ON user_photos
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 2. Add missing columns and trigger to event_organizers
ALTER TABLE event_organizers
ADD COLUMN IF NOT EXISTS company_name VARCHAR(150),
ADD COLUMN IF NOT EXISTS company_address VARCHAR(255),
ADD COLUMN IF NOT EXISTS business_email VARCHAR(255) UNIQUE,
ADD COLUMN IF NOT EXISTS business_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

DROP TRIGGER IF EXISTS update_event_organizers_updated_at ON event_organizers;
CREATE TRIGGER update_event_organizers_updated_at
BEFORE UPDATE ON event_organizers
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 3. Update coordinators table - add specialization and make user_id unique
ALTER TABLE coordinators
ADD COLUMN IF NOT EXISTS specialization VARCHAR(100),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Make user_id unique (if not already)
ALTER TABLE coordinators DROP CONSTRAINT IF EXISTS unique_coordinator_user;
ALTER TABLE coordinators
ADD CONSTRAINT unique_coordinator_user UNIQUE (user_id);

DROP TRIGGER IF EXISTS update_coordinators_updated_at ON coordinators;
CREATE TRIGGER update_coordinators_updated_at
BEFORE UPDATE ON coordinators
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 4. Add missing columns and trigger to venue_administrators
ALTER TABLE venue_administrators
ADD COLUMN IF NOT EXISTS assigned_venue_id INTEGER,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

DROP TRIGGER IF EXISTS update_venue_administrators_updated_at ON venue_administrators;
CREATE TRIGGER update_venue_administrators_updated_at
BEFORE UPDATE ON venue_administrators
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 5. Add missing triggers to otp and password_reset
DROP TRIGGER IF EXISTS update_otp_updated_at ON otp;
CREATE TRIGGER update_otp_updated_at
BEFORE UPDATE ON otp
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_password_reset_updated_at ON password_reset;
CREATE TRIGGER update_password_reset_updated_at
BEFORE UPDATE ON password_reset
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Add missing columns to password_reset
ALTER TABLE password_reset
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- 6. Add missing columns and trigger to email_verification
ALTER TABLE email_verification
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

DROP TRIGGER IF EXISTS update_email_verification_updated_at ON email_verification;
CREATE TRIGGER update_email_verification_updated_at
BEFORE UPDATE ON email_verification
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Add missing index
DROP INDEX IF EXISTS idx_email_verification_expiry CASCADE;
CREATE INDEX idx_email_verification_expiry ON email_verification (expires_at);

-- Add missing index to otp
DROP INDEX IF EXISTS idx_otp_expiry CASCADE;
CREATE INDEX idx_otp_expiry ON otp (otp_expiry);

-- ===== CREATE NEW TABLES =====

-- 7. Customers table
DROP TABLE IF EXISTS customers CASCADE;
CREATE TABLE customers (
  customer_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER NOT NULL UNIQUE,
  preferences   TEXT DEFAULT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_customers_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_customers_updated_at ON customers;
CREATE TRIGGER update_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 8. Administrators table
DROP TABLE IF EXISTS administrators CASCADE;
CREATE TABLE administrators (
  admin_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          INTEGER NOT NULL UNIQUE,
  position         VARCHAR(100) NOT NULL DEFAULT 'System Administrator',
  role_description TEXT NOT NULL,
  admin_notes      TEXT DEFAULT NULL,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_administrators_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_administrators_updated_at ON administrators;
CREATE TRIGGER update_administrators_updated_at
BEFORE UPDATE ON administrators
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 9. Event themes table
DROP TABLE IF EXISTS event_themes CASCADE;
CREATE TABLE event_themes (
  event_theme_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  theme_name       VARCHAR(100) NOT NULL UNIQUE,
  theme_description TEXT NOT NULL,
  primary_color    VARCHAR(100) NOT NULL,
  secondary_color  VARCHAR(100) DEFAULT NULL,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS update_event_themes_updated_at ON event_themes;
CREATE TRIGGER update_event_themes_updated_at
BEFORE UPDATE ON event_themes
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 10. Event categories table
DROP TABLE IF EXISTS event_categories CASCADE;
CREATE TABLE event_categories (
  category_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(50) NOT NULL UNIQUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS update_event_categories_updated_at ON event_categories;
CREATE TRIGGER update_event_categories_updated_at
BEFORE UPDATE ON event_categories
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 11. Decoration styles table
DROP TABLE IF EXISTS decoration_styles CASCADE;
CREATE TABLE decoration_styles (
  decoration_style_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  style_name          VARCHAR(50) NOT NULL UNIQUE,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS update_decoration_styles_updated_at ON decoration_styles;
CREATE TRIGGER update_decoration_styles_updated_at
BEFORE UPDATE ON decoration_styles
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 12. Lighting styles table
DROP TABLE IF EXISTS lighting_styles CASCADE;
CREATE TABLE lighting_styles (
  lighting_style_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  style_name        VARCHAR(50) NOT NULL UNIQUE,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS update_lighting_styles_updated_at ON lighting_styles;
CREATE TRIGGER update_lighting_styles_updated_at
BEFORE UPDATE ON lighting_styles
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 13. Event theme categories junction table
DROP TABLE IF EXISTS event_theme_categories CASCADE;
CREATE TABLE event_theme_categories (
  theme_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_theme_id    INTEGER NOT NULL,
  category_id       INTEGER NOT NULL,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_etc_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE CASCADE,
  CONSTRAINT fk_etc_category FOREIGN KEY (category_id) REFERENCES event_categories(category_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_event_theme_categories_updated_at ON event_theme_categories;
CREATE TRIGGER update_event_theme_categories_updated_at
BEFORE UPDATE ON event_theme_categories
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 14. Event theme decorations junction table
DROP TABLE IF EXISTS event_theme_decorations CASCADE;
CREATE TABLE event_theme_decorations (
  theme_decoration_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_theme_id       INTEGER NOT NULL,
  decoration_style_id  INTEGER NOT NULL,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_etd_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE CASCADE,
  CONSTRAINT fk_etd_decoration FOREIGN KEY (decoration_style_id) REFERENCES decoration_styles(decoration_style_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_event_theme_decorations_updated_at ON event_theme_decorations;
CREATE TRIGGER update_event_theme_decorations_updated_at
BEFORE UPDATE ON event_theme_decorations
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 15. Event theme lighting junction table
DROP TABLE IF EXISTS event_theme_lighting CASCADE;
CREATE TABLE event_theme_lighting (
  theme_lighting_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_theme_id     INTEGER NOT NULL,
  lighting_style_id  INTEGER NOT NULL,
  created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_etl_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE CASCADE,
  CONSTRAINT fk_etl_lighting FOREIGN KEY (lighting_style_id) REFERENCES lighting_styles(lighting_style_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_event_theme_lighting_updated_at ON event_theme_lighting;
CREATE TRIGGER update_event_theme_lighting_updated_at
BEFORE UPDATE ON event_theme_lighting
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 16. Event theme accent colors table
DROP TABLE IF EXISTS event_theme_accent_colors CASCADE;
CREATE TABLE event_theme_accent_colors (
  accent_color_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_theme_id  INTEGER NOT NULL,
  color_value     VARCHAR(100) NOT NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_etac_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_event_theme_accent_colors_updated_at ON event_theme_accent_colors;
CREATE TRIGGER update_event_theme_accent_colors_updated_at
BEFORE UPDATE ON event_theme_accent_colors
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 17. Event theme images table
DROP TABLE IF EXISTS event_theme_images CASCADE;
CREATE TABLE event_theme_images (
  image_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_theme_id INTEGER NOT NULL,
  image_path     VARCHAR(255) NOT NULL,
  is_thumbnail   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_eti_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE CASCADE
);
DROP INDEX IF EXISTS idx_event_theme_id CASCADE;
CREATE INDEX idx_event_theme_id ON event_theme_images (event_theme_id);

DROP TRIGGER IF EXISTS update_event_theme_images_updated_at ON event_theme_images;
CREATE TRIGGER update_event_theme_images_updated_at
BEFORE UPDATE ON event_theme_images
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 18. Venue types table
DROP TABLE IF EXISTS venue_types CASCADE;
CREATE TABLE venue_types (
  venue_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name     VARCHAR(100) NOT NULL UNIQUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS update_venue_types_updated_at ON venue_types;
CREATE TRIGGER update_venue_types_updated_at
BEFORE UPDATE ON venue_types
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 20. Venue venue types junction table
DROP TABLE IF EXISTS venue_venue_types CASCADE;
CREATE TABLE venue_venue_types (
  venue_type_link_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id           INTEGER NOT NULL,
  venue_type_id      INTEGER NOT NULL,
  created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_venue_type UNIQUE (venue_id, venue_type_id),
  CONSTRAINT fk_vvt_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_vvt_type FOREIGN KEY (venue_type_id) REFERENCES venue_types(venue_type_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_venue_types_updated_at ON venue_venue_types;
CREATE TRIGGER update_venue_venue_types_updated_at
BEFORE UPDATE ON venue_venue_types
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 21. Venue contacts table
DROP TABLE IF EXISTS venue_contacts CASCADE;
CREATE TABLE venue_contacts (
  contact_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id      INTEGER NOT NULL,
  contact_type  venue_contact_type NOT NULL,
  contact_value VARCHAR(100) NOT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vc_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_contacts_updated_at ON venue_contacts;
CREATE TRIGGER update_venue_contacts_updated_at
BEFORE UPDATE ON venue_contacts
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 22. Venue specifications table
DROP TABLE IF EXISTS venue_specifications CASCADE;
CREATE TABLE venue_specifications (
  specification_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id            INTEGER NOT NULL,
  specification_name  VARCHAR(100) NOT NULL,
  specification_value VARCHAR(100) NOT NULL,
  notes               TEXT DEFAULT NULL,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_venue_spec UNIQUE (venue_id, specification_name),
  CONSTRAINT fk_vs_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_specifications_updated_at ON venue_specifications;
CREATE TRIGGER update_venue_specifications_updated_at
BEFORE UPDATE ON venue_specifications
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 23. Venue allowed event types table
DROP TABLE IF EXISTS venue_allowed_event_types CASCADE;
CREATE TABLE venue_allowed_event_types (
  venue_event_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id            INTEGER NOT NULL,
  category_id         INTEGER NOT NULL,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_venue_category UNIQUE (venue_id, category_id),
  CONSTRAINT fk_vaet_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_vaet_category FOREIGN KEY (category_id) REFERENCES event_categories(category_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_allowed_event_types_updated_at ON venue_allowed_event_types;
CREATE TRIGGER update_venue_allowed_event_types_updated_at
BEFORE UPDATE ON venue_allowed_event_types
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 24. Venue images table
DROP TABLE IF EXISTS venue_images CASCADE;
CREATE TABLE venue_images (
  image_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id     INTEGER NOT NULL,
  image_path   VARCHAR(255) NOT NULL,
  is_thumbnail BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vi_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);
DROP INDEX IF EXISTS idx_venue_id CASCADE;
CREATE INDEX idx_venue_id ON venue_images (venue_id);

DROP TRIGGER IF EXISTS update_venue_images_updated_at ON venue_images;
CREATE TRIGGER update_venue_images_updated_at
BEFORE UPDATE ON venue_images
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 25. Venue facilities table
DROP TABLE IF EXISTS venue_facilities CASCADE;
CREATE TABLE venue_facilities (
  facility_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id      INTEGER NOT NULL,
  facility_name VARCHAR(100) NOT NULL,
  description   TEXT DEFAULT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vf_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_facilities_updated_at ON venue_facilities;
CREATE TRIGGER update_venue_facilities_updated_at
BEFORE UPDATE ON venue_facilities
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 26. Venue rules table
DROP TABLE IF EXISTS venue_rules CASCADE;
CREATE TABLE venue_rules (
  rule_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id    INTEGER NOT NULL,
  rule_text   TEXT NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vr_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_rules_updated_at ON venue_rules;
CREATE TRIGGER update_venue_rules_updated_at
BEFORE UPDATE ON venue_rules
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 27. Venue floor plans table
DROP TABLE IF EXISTS venue_floor_plans CASCADE;
CREATE TABLE venue_floor_plans (
  floor_plan_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id        INTEGER NOT NULL,
  floor_plan_file VARCHAR(255) NOT NULL,
  floor_plan_type VARCHAR(100) NOT NULL,
  description     TEXT DEFAULT NULL,
  length          DECIMAL(5, 2) NOT NULL,
  width           DECIMAL(5, 2) NOT NULL,
  height          DECIMAL(5, 2) NOT NULL,
  area_sqm        DECIMAL(7, 2) NOT NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vfp_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_floor_plans_updated_at ON venue_floor_plans;
CREATE TRIGGER update_venue_floor_plans_updated_at
BEFORE UPDATE ON venue_floor_plans
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 28. Venue doors table
DROP TABLE IF EXISTS venue_doors CASCADE;
CREATE TABLE venue_doors (
  door_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id        INTEGER NOT NULL,
  door_type       door_type_enum NOT NULL,
  width           DECIMAL(5, 2) NOT NULL,
  height          DECIMAL(5, 2) NOT NULL,
  door_offset     DECIMAL(5, 2) NOT NULL,
  corner_position door_corner_enum NOT NULL DEFAULT 'Center',
  swing_direction door_swing_enum NOT NULL DEFAULT 'Inward',
  hinge_position  door_hinge_enum NOT NULL DEFAULT 'Left',
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vd_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_doors_updated_at ON venue_doors;
CREATE TRIGGER update_venue_doors_updated_at
BEFORE UPDATE ON venue_doors
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 29. Venue base rates table
DROP TABLE IF EXISTS venue_base_rates CASCADE;
CREATE TABLE venue_base_rates (
  rate_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id       INTEGER NOT NULL,
  rate_type      rate_type_enum NOT NULL,
  base_price     DECIMAL(12, 2) NOT NULL,
  weekend_price  DECIMAL(12, 2) NOT NULL,
  holiday_price  DECIMAL(12, 2) NOT NULL,
  included_hours INTEGER NOT NULL,
  min_hours      INTEGER NOT NULL DEFAULT 2,
  notes          TEXT DEFAULT NULL,
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vbr_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_base_rates_updated_at ON venue_base_rates;
CREATE TRIGGER update_venue_base_rates_updated_at
BEFORE UPDATE ON venue_base_rates
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 30. Venue overtime rates table
DROP TABLE IF EXISTS venue_overtime_rates CASCADE;
CREATE TABLE venue_overtime_rates (
  overtime_rate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id         INTEGER NOT NULL,
  rate_type        rate_type_enum NOT NULL,
  start_hour       INTEGER NOT NULL,
  end_hour         INTEGER DEFAULT NULL,
  price_per_hour   DECIMAL(12, 2) NOT NULL,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vor_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_overtime_rates_updated_at ON venue_overtime_rates;
CREATE TRIGGER update_venue_overtime_rates_updated_at
BEFORE UPDATE ON venue_overtime_rates
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 31. Venue packages table
DROP TABLE IF EXISTS venue_packages CASCADE;
CREATE TABLE venue_packages (
  package_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id      INTEGER NOT NULL,
  package_name  VARCHAR(150) NOT NULL,
  description   TEXT NOT NULL,
  duration_hours INTEGER NOT NULL,
  duration_days INTEGER DEFAULT NULL,
  base_price    DECIMAL(12, 2) NOT NULL,
  min_hours     INTEGER NOT NULL,
  notes         TEXT DEFAULT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_package_name UNIQUE (venue_id, package_name),
  CONSTRAINT fk_vp_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);
DROP INDEX IF EXISTS idx_package_name CASCADE;
CREATE INDEX idx_package_name ON venue_packages (package_name);

DROP TRIGGER IF EXISTS update_venue_packages_updated_at ON venue_packages;
CREATE TRIGGER update_venue_packages_updated_at
BEFORE UPDATE ON venue_packages
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 32. Venue package inclusions table
DROP TABLE IF EXISTS venue_package_inclusions CASCADE;
CREATE TABLE venue_package_inclusions (
  inclusion_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id    INTEGER NOT NULL,
  inclusion_name VARCHAR(150) NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vpi_package FOREIGN KEY (package_id) REFERENCES venue_packages(package_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_package_inclusions_updated_at ON venue_package_inclusions;
CREATE TRIGGER update_venue_package_inclusions_updated_at
BEFORE UPDATE ON venue_package_inclusions
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 33. Venue seasonal pricing table
DROP TABLE IF EXISTS venue_seasonal_pricing CASCADE;
CREATE TABLE venue_seasonal_pricing (
  seasonal_price_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id          INTEGER NOT NULL,
  rate_type         seasonal_rate_type_enum NOT NULL,
  package_id        INTEGER DEFAULT NULL,
  season_name       VARCHAR(100) NOT NULL,
  start_date        DATE NOT NULL,
  end_date          DATE NOT NULL,
  modifier_type     modifier_type_enum NOT NULL,
  modifier_value    DECIMAL(10, 2) NOT NULL,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vsp_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_vsp_package FOREIGN KEY (package_id) REFERENCES venue_packages(package_id) ON DELETE SET NULL
);
DROP INDEX IF EXISTS idx_season_name CASCADE;
CREATE INDEX idx_season_name ON venue_seasonal_pricing (season_name);

DROP TRIGGER IF EXISTS update_venue_seasonal_pricing_updated_at ON venue_seasonal_pricing;
CREATE TRIGGER update_venue_seasonal_pricing_updated_at
BEFORE UPDATE ON venue_seasonal_pricing
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 34. Package types table
DROP TABLE IF EXISTS package_types CASCADE;
CREATE TABLE package_types (
  package_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS update_package_types_updated_at ON package_types;
CREATE TRIGGER update_package_types_updated_at
BEFORE UPDATE ON package_types
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 35. Event packages table
DROP TABLE IF EXISTS event_packages CASCADE;
CREATE TABLE event_packages (
  package_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_type_id INTEGER NOT NULL,
  package_name VARCHAR(150) NOT NULL,
  description TEXT NOT NULL,
  excess_pax_price DECIMAL(10,2) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ep_package_type FOREIGN KEY (package_type_id) REFERENCES package_types(package_type_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_event_packages_updated_at ON event_packages;
CREATE TRIGGER update_event_packages_updated_at
BEFORE UPDATE ON event_packages
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 36. Package pax prices table
DROP TABLE IF EXISTS package_pax_prices CASCADE;
CREATE TABLE package_pax_prices (
  pax_price_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id INTEGER NOT NULL,
  pax_count INTEGER NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ppp_package FOREIGN KEY (package_id) REFERENCES event_packages(package_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_package_pax_prices_updated_at ON package_pax_prices;
CREATE TRIGGER update_package_pax_prices_updated_at
BEFORE UPDATE ON package_pax_prices
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 37. Service categories table
DROP TABLE IF EXISTS service_categories CASCADE;
CREATE TABLE service_categories (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS update_service_categories_updated_at ON service_categories;
CREATE TRIGGER update_service_categories_updated_at
BEFORE UPDATE ON service_categories
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 38. Services table
DROP TABLE IF EXISTS services CASCADE;
CREATE TABLE services (
  service_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INTEGER NOT NULL,
  service_name VARCHAR(150) NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_svc_category FOREIGN KEY (category_id) REFERENCES service_categories(category_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_services_updated_at ON services;
CREATE TRIGGER update_services_updated_at
BEFORE UPDATE ON services
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 39. Package services junction table
DROP TABLE IF EXISTS package_services CASCADE;
CREATE TABLE package_services (
  package_id INTEGER NOT NULL,
  service_id INTEGER NOT NULL,
  PRIMARY KEY (package_id, service_id),
  CONSTRAINT fk_ps_package FOREIGN KEY (package_id) REFERENCES event_packages(package_id) ON DELETE CASCADE,
  CONSTRAINT fk_ps_service FOREIGN KEY (service_id) REFERENCES services(service_id) ON DELETE CASCADE
);

-- 40. Add-on categories table
DROP TABLE IF EXISTS add_on_categories CASCADE;
CREATE TABLE add_on_categories (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS update_add_on_categories_updated_at ON add_on_categories;
CREATE TRIGGER update_add_on_categories_updated_at
BEFORE UPDATE ON add_on_categories
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 41. Add-ons table
DROP TABLE IF EXISTS add_ons CASCADE;
CREATE TABLE add_ons (
  add_on_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INTEGER NOT NULL,
  add_on_name VARCHAR(150) NOT NULL,
  description TEXT NOT NULL,
  price_type price_type_enum NOT NULL,
  default_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ao_category FOREIGN KEY (category_id) REFERENCES add_on_categories(category_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_add_ons_updated_at ON add_ons;
CREATE TRIGGER update_add_ons_updated_at
BEFORE UPDATE ON add_ons
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 42. Package add-ons junction table
DROP TABLE IF EXISTS package_add_ons CASCADE;
CREATE TABLE package_add_ons (
  package_id INTEGER NOT NULL,
  add_on_id INTEGER NOT NULL,
  PRIMARY KEY (package_id, add_on_id),
  CONSTRAINT fk_pao_package FOREIGN KEY (package_id) REFERENCES event_packages(package_id) ON DELETE CASCADE,
  CONSTRAINT fk_pao_addon FOREIGN KEY (add_on_id) REFERENCES add_ons(add_on_id) ON DELETE CASCADE
);

-- 43. Venues table
DROP TABLE IF EXISTS venues CASCADE;
CREATE TABLE venues (
  venue_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_name    VARCHAR(150) NOT NULL UNIQUE,
  description   TEXT NOT NULL,
  street_address VARCHAR(255) NOT NULL,
  barangay      VARCHAR(100) NOT NULL,
  city          VARCHAR(100) NOT NULL,
  province      VARCHAR(100) NOT NULL,
  zip_code      VARCHAR(10) NOT NULL,
  country       VARCHAR(100) NOT NULL DEFAULT 'Philippines',
  max_capacity  INTEGER NOT NULL,
  created_by    INTEGER NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_venues_creator FOREIGN KEY (created_by) REFERENCES users(user_id) ON DELETE CASCADE
);
DROP INDEX IF EXISTS idx_venue_name CASCADE;
CREATE INDEX idx_venue_name ON venues (venue_name);

DROP TRIGGER IF EXISTS update_venues_updated_at ON venues;
CREATE TRIGGER update_venues_updated_at
BEFORE UPDATE ON venues
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 44. Venue admin assignments table
DROP TABLE IF EXISTS venue_admin_assignments CASCADE;
CREATE TABLE venue_admin_assignments (
  assignment_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id       INTEGER NOT NULL,
  venue_admin_id INTEGER NOT NULL,
  is_owner       BOOLEAN NOT NULL DEFAULT TRUE,
  assigned_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  revoked_at     TIMESTAMP DEFAULT NULL,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_venue_admin UNIQUE (venue_id, venue_admin_id),
  CONSTRAINT fk_vaa_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_vaa_admin FOREIGN KEY (venue_admin_id) REFERENCES venue_administrators(venue_admin_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_admin_assignments_updated_at ON venue_admin_assignments;
CREATE TRIGGER update_venue_admin_assignments_updated_at
BEFORE UPDATE ON venue_admin_assignments
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 45. Bookings table
DROP TABLE IF EXISTS bookings CASCADE;
CREATE TABLE bookings (
  booking_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coordinator_id INTEGER NOT NULL,
  venue_id       INTEGER DEFAULT NULL,
  venue_type     VARCHAR(50) NOT NULL,
  event_date     DATE NOT NULL,
  time_start     TIME NOT NULL,
  time_end       TIME NOT NULL,
  guest_capacity INTEGER NOT NULL,
  booking_status VARCHAR(50) NOT NULL DEFAULT 'pending',
  notes          TEXT DEFAULT NULL,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bookings_coordinator FOREIGN KEY (coordinator_id) REFERENCES coordinators(coordinator_id) ON DELETE CASCADE,
  CONSTRAINT fk_bookings_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE SET NULL
);

DROP TRIGGER IF EXISTS update_bookings_updated_at ON bookings;
CREATE TRIGGER update_bookings_updated_at
BEFORE UPDATE ON bookings
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 46. Booking themes table
DROP TABLE IF EXISTS booking_themes CASCADE;
CREATE TABLE booking_themes (
  booking_theme_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id        INTEGER NOT NULL UNIQUE,
  theme_type        VARCHAR(50) NOT NULL DEFAULT 'predefined',
  event_theme_id    INTEGER DEFAULT NULL,
  custom_theme_name VARCHAR(100) DEFAULT NULL,
  primary_color     VARCHAR(50) DEFAULT NULL,
  secondary_color   VARCHAR(50) DEFAULT NULL,
  accent_color      VARCHAR(50) DEFAULT NULL,
  notes             TEXT DEFAULT NULL,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bt_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_bt_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE SET NULL
);

DROP TRIGGER IF EXISTS update_booking_themes_updated_at ON booking_themes;
CREATE TRIGGER update_booking_themes_updated_at
BEFORE UPDATE ON booking_themes
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 47. Booking pricing table
DROP TABLE IF EXISTS booking_pricing CASCADE;
CREATE TABLE booking_pricing (
  pricing_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id  INTEGER NOT NULL UNIQUE,
  package_id  INTEGER NOT NULL,
  selected_pax INTEGER NOT NULL,
  base_price  DECIMAL(12, 2) NOT NULL,
  excess_pax  INTEGER NOT NULL DEFAULT 0,
  excess_price DECIMAL(12, 2) DEFAULT 0,
  total_amount DECIMAL(12, 2) NOT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bp_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_bp_package FOREIGN KEY (package_id) REFERENCES event_packages(package_id)
);

DROP TRIGGER IF EXISTS update_booking_pricing_updated_at ON booking_pricing;
CREATE TRIGGER update_booking_pricing_updated_at
BEFORE UPDATE ON booking_pricing
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 48. Booking add-ons table
DROP TABLE IF EXISTS booking_add_ons CASCADE;
CREATE TABLE booking_add_ons (
  booking_add_on_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id        INTEGER NOT NULL,
  add_on_id         INTEGER NOT NULL,
  quantity          INTEGER DEFAULT 1,
  unit_price        DECIMAL(12, 2) NOT NULL,
  total_price       DECIMAL(12, 2) NOT NULL,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_booking_addon UNIQUE (booking_id, add_on_id),
  CONSTRAINT fk_bao_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_bao_addon FOREIGN KEY (add_on_id) REFERENCES add_ons(add_on_id)
);

DROP TRIGGER IF EXISTS update_booking_add_ons_updated_at ON booking_add_ons;
CREATE TRIGGER update_booking_add_ons_updated_at
BEFORE UPDATE ON booking_add_ons
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 49. Custom venues table
DROP TABLE IF EXISTS custom_venues CASCADE;
CREATE TABLE custom_venues (
  custom_venue_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id        INTEGER NOT NULL UNIQUE,
  custom_venue_name VARCHAR(255) NOT NULL,
  street_address    VARCHAR(255) NOT NULL,
  barangay          VARCHAR(100) NOT NULL,
  city              VARCHAR(100) NOT NULL,
  province          VARCHAR(100) NOT NULL,
  zip_code          VARCHAR(10) NOT NULL,
  country           VARCHAR(100) NOT NULL DEFAULT 'Philippines',
  custom_venue_capacity INTEGER NOT NULL,
  base_price        DECIMAL(12, 2) NOT NULL DEFAULT 0,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cv_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_custom_venues_updated_at ON custom_venues;
CREATE TRIGGER update_custom_venues_updated_at
BEFORE UPDATE ON custom_venues
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 50. Projects table
DROP TABLE IF EXISTS projects CASCADE;
CREATE TABLE projects (
  project_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id       INTEGER NOT NULL,
  booking_theme_id INTEGER DEFAULT NULL,
  project_name     VARCHAR(255) NOT NULL,
  organizer_id     INTEGER NOT NULL,
  customer_id      INTEGER NOT NULL,
  project_status   VARCHAR(50) NOT NULL,
  notes            TEXT DEFAULT NULL,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_proj_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_proj_theme FOREIGN KEY (booking_theme_id) REFERENCES booking_themes(booking_theme_id) ON DELETE SET NULL,
  CONSTRAINT fk_proj_organizer FOREIGN KEY (organizer_id) REFERENCES event_organizers(organizer_id) ON DELETE CASCADE,
  CONSTRAINT fk_proj_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_projects_updated_at ON projects;
CREATE TRIGGER update_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 51. Reschedules table
DROP TABLE IF EXISTS reschedules CASCADE;
CREATE TABLE reschedules (
  reschedule_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id       INTEGER NOT NULL,
  project_id       INTEGER NOT NULL,
  old_event_date   DATE NOT NULL,
  old_time_start   TIME NOT NULL,
  old_time_end     TIME NOT NULL,
  new_event_date   DATE NOT NULL,
  new_time_start   TIME NOT NULL,
  new_time_end     TIME NOT NULL,
  requested_by     INTEGER NOT NULL,
  reason           TEXT DEFAULT NULL,
  approved_by      INTEGER DEFAULT NULL,
  approved_at      TIMESTAMP DEFAULT NULL,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rs_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_rs_project FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE CASCADE,
  CONSTRAINT fk_rs_requested FOREIGN KEY (requested_by) REFERENCES coordinators(coordinator_id) ON DELETE CASCADE,
  CONSTRAINT fk_rs_approved FOREIGN KEY (approved_by) REFERENCES venue_administrators(venue_admin_id) ON DELETE SET NULL
);

-- 52. Reviews table
DROP TABLE IF EXISTS reviews CASCADE;
CREATE TABLE reviews (
  review_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id   INTEGER NOT NULL,
  booking_id   INTEGER NOT NULL,
  customer_id  INTEGER NOT NULL,
  organizer_id INTEGER NOT NULL,
  venue_id     INTEGER DEFAULT NULL,
  rating       SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review_text  TEXT DEFAULT NULL,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_review UNIQUE (project_id, customer_id),
  CONSTRAINT fk_rev_project FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE CASCADE,
  CONSTRAINT fk_rev_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_rev_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE,
  CONSTRAINT fk_rev_organizer FOREIGN KEY (organizer_id) REFERENCES event_organizers(organizer_id) ON DELETE CASCADE,
  CONSTRAINT fk_rev_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE SET NULL
);

DROP TRIGGER IF EXISTS update_reviews_updated_at ON reviews;
CREATE TRIGGER update_reviews_updated_at
BEFORE UPDATE ON reviews
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 53. Venue direct bookings table
DROP TABLE IF EXISTS venue_direct_bookings CASCADE;
CREATE TABLE venue_direct_bookings (
  direct_booking_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id           INTEGER NOT NULL,
  venue_admin_id     INTEGER NOT NULL,
  client_name        VARCHAR(255) NOT NULL,
  client_email       VARCHAR(255) NOT NULL,
  client_contact     VARCHAR(20) NOT NULL,
  event_name         VARCHAR(255) NOT NULL,
  event_date         DATE NOT NULL,
  time_start         TIME NOT NULL,
  time_end           TIME NOT NULL,
  guest_capacity     INTEGER NOT NULL,
  organizer_name     VARCHAR(255) DEFAULT NULL,
  organizer_contact  VARCHAR(20) DEFAULT NULL,
  status             VARCHAR(50) NOT NULL DEFAULT 'confirmed',
  notes              TEXT DEFAULT NULL,
  created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vdb_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_vdb_admin FOREIGN KEY (venue_admin_id) REFERENCES venue_administrators(venue_admin_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_direct_bookings_updated_at ON venue_direct_bookings;
CREATE TRIGGER update_venue_direct_bookings_updated_at
BEFORE UPDATE ON venue_direct_bookings
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 54. Direct booking themes table
DROP TABLE IF EXISTS direct_booking_themes CASCADE;
CREATE TABLE direct_booking_themes (
  direct_booking_theme_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  direct_booking_id       INTEGER NOT NULL UNIQUE,
  theme_type              VARCHAR(50) NOT NULL DEFAULT 'predefined',
  event_theme_id          INTEGER DEFAULT NULL,
  custom_theme_name       VARCHAR(100) DEFAULT NULL,
  primary_color           VARCHAR(50) DEFAULT NULL,
  secondary_color         VARCHAR(50) DEFAULT NULL,
  accent_color            VARCHAR(50) DEFAULT NULL,
  notes                   TEXT DEFAULT NULL,
  created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_dbt_booking FOREIGN KEY (direct_booking_id) REFERENCES venue_direct_bookings(direct_booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_dbt_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE SET NULL
);

DROP TRIGGER IF EXISTS update_direct_booking_themes_updated_at ON direct_booking_themes;
CREATE TRIGGER update_direct_booking_themes_updated_at
BEFORE UPDATE ON direct_booking_themes
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 55. Venue direct reschedules table
DROP TABLE IF EXISTS venue_direct_reschedules CASCADE;
CREATE TABLE venue_direct_reschedules (
  reschedule_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  direct_booking_id      INTEGER NOT NULL,
  old_event_date         DATE NOT NULL,
  old_time_start         TIME NOT NULL,
  old_time_end           TIME NOT NULL,
  old_guest_capacity     INTEGER NOT NULL,
  new_event_date         DATE NOT NULL,
  new_time_start         TIME NOT NULL,
  new_time_end           TIME NOT NULL,
  new_guest_capacity     INTEGER NOT NULL,
  requested_by           INTEGER NOT NULL,
  reason                 TEXT DEFAULT NULL,
  approved_by            INTEGER DEFAULT NULL,
  approved_at            TIMESTAMP DEFAULT NULL,
  created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vdr_booking FOREIGN KEY (direct_booking_id) REFERENCES venue_direct_bookings(direct_booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_vdr_requested FOREIGN KEY (requested_by) REFERENCES venue_administrators(venue_admin_id) ON DELETE CASCADE,
  CONSTRAINT fk_vdr_approved FOREIGN KEY (approved_by) REFERENCES venue_administrators(venue_admin_id) ON DELETE SET NULL
);

DROP TRIGGER IF EXISTS update_venue_direct_reschedules_updated_at ON venue_direct_reschedules;
CREATE TRIGGER update_venue_direct_reschedules_updated_at
BEFORE UPDATE ON venue_direct_reschedules
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 56. Venue blocked dates table
DROP TABLE IF EXISTS venue_blocked_dates CASCADE;
CREATE TABLE venue_blocked_dates (
  blocked_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id    INTEGER NOT NULL,
  venue_admin_id INTEGER NOT NULL,
  start_date  DATE NOT NULL,
  end_date    DATE NOT NULL,
  reason      VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_block UNIQUE (venue_id, start_date, end_date),
  CONSTRAINT fk_vbd_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_vbd_admin FOREIGN KEY (venue_admin_id) REFERENCES venue_administrators(venue_admin_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_blocked_dates_updated_at ON venue_blocked_dates;
CREATE TRIGGER update_venue_blocked_dates_updated_at
BEFORE UPDATE ON venue_blocked_dates
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 57. Venue overtime logs table
DROP TABLE IF EXISTS venue_overtime_logs CASCADE;
CREATE TABLE venue_overtime_logs (
  overtime_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id      INTEGER NOT NULL,
  coordinator_id  INTEGER DEFAULT NULL,
  venue_admin_id  INTEGER DEFAULT NULL,
  overtime_hours  DECIMAL(5, 2) NOT NULL,
  rate_per_hour   DECIMAL(12, 2) NOT NULL,
  total_amount    DECIMAL(12, 2) NOT NULL,
  notes           TEXT DEFAULT NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vol_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_vol_coordinator FOREIGN KEY (coordinator_id) REFERENCES coordinators(coordinator_id) ON DELETE CASCADE,
  CONSTRAINT fk_vol_admin FOREIGN KEY (venue_admin_id) REFERENCES venue_administrators(venue_admin_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_venue_overtime_logs_updated_at ON venue_overtime_logs;
CREATE TRIGGER update_venue_overtime_logs_updated_at
BEFORE UPDATE ON venue_overtime_logs
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 58. Booking adjustments table
DROP TABLE IF EXISTS booking_adjustments CASCADE;
CREATE TABLE booking_adjustments (
  adjustment_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id        INTEGER DEFAULT NULL,
  direct_booking_id INTEGER DEFAULT NULL,
  venue_id          INTEGER NOT NULL,
  coordinator_id    INTEGER DEFAULT NULL,
  venue_admin_id    INTEGER DEFAULT NULL,
  adjustment_type   VARCHAR(50) NOT NULL,
  adjustment_method VARCHAR(50) NOT NULL DEFAULT 'fixed',
  description       VARCHAR(255) DEFAULT NULL,
  amount            DECIMAL(12, 2) NOT NULL,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ba_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_ba_direct_booking FOREIGN KEY (direct_booking_id) REFERENCES venue_direct_bookings(direct_booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_ba_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_ba_coordinator FOREIGN KEY (coordinator_id) REFERENCES coordinators(coordinator_id) ON DELETE CASCADE,
  CONSTRAINT fk_ba_admin FOREIGN KEY (venue_admin_id) REFERENCES venue_administrators(venue_admin_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_booking_adjustments_updated_at ON booking_adjustments;
CREATE TRIGGER update_booking_adjustments_updated_at
BEFORE UPDATE ON booking_adjustments
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 59. Booking billing summary table
DROP TABLE IF EXISTS booking_billing_summary CASCADE;
CREATE TABLE booking_billing_summary (
  billing_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id          INTEGER NOT NULL UNIQUE,
  base_amount         DECIMAL(12, 2) NOT NULL,
  overtime_amount     DECIMAL(12, 2) DEFAULT 0,
  total_discounts     DECIMAL(12, 2) DEFAULT 0,
  total_extra_charges DECIMAL(12, 2) DEFAULT 0,
  final_amount        DECIMAL(12, 2) NOT NULL,
  coordinator_id      INTEGER DEFAULT NULL,
  venue_admin_id      INTEGER DEFAULT NULL,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bbs_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
  CONSTRAINT fk_bbs_coordinator FOREIGN KEY (coordinator_id) REFERENCES coordinators(coordinator_id) ON DELETE CASCADE,
  CONSTRAINT fk_bbs_admin FOREIGN KEY (venue_admin_id) REFERENCES venue_administrators(venue_admin_id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS update_booking_billing_summary_updated_at ON booking_billing_summary;
CREATE TRIGGER update_booking_billing_summary_updated_at
BEFORE UPDATE ON booking_billing_summary
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ===== DISABLE ROW LEVEL SECURITY ON NEW TABLES =====
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE administrators DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_themes DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE decoration_styles DISABLE ROW LEVEL SECURITY;
ALTER TABLE lighting_styles DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_theme_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_theme_decorations DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_theme_lighting DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_theme_accent_colors DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_theme_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE venues DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_admin_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_venue_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_specifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_allowed_event_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_facilities DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_floor_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_doors DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_base_rates DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_overtime_rates DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_packages DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_package_inclusions DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_seasonal_pricing DISABLE ROW LEVEL SECURITY;
ALTER TABLE package_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_packages DISABLE ROW LEVEL SECURITY;
ALTER TABLE package_pax_prices DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE services DISABLE ROW LEVEL SECURITY;
ALTER TABLE package_services DISABLE ROW LEVEL SECURITY;
ALTER TABLE add_on_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE add_ons DISABLE ROW LEVEL SECURITY;
ALTER TABLE package_add_ons DISABLE ROW LEVEL SECURITY;
ALTER TABLE bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE booking_themes DISABLE ROW LEVEL SECURITY;
ALTER TABLE booking_pricing DISABLE ROW LEVEL SECURITY;
ALTER TABLE booking_add_ons DISABLE ROW LEVEL SECURITY;
ALTER TABLE custom_venues DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE reschedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_direct_bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE direct_booking_themes DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_direct_reschedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_blocked_dates DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_overtime_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE booking_adjustments DISABLE ROW LEVEL SECURITY;
ALTER TABLE booking_billing_summary DISABLE ROW LEVEL SECURITY;

-- ===== MIGRATION COMPLETE =====
-- Your database is now updated to match supabase_schema_new.sql
-- All new tables, triggers, and enums have been created.
