-- 0. (Optional) Drop things if re-running during development
-- DROP TABLE IF EXISTS email_verification, password_reset, otp, venue_administrators, coordinators, event_organizers, user_photos, users CASCADE;
-- DROP TYPE IF EXISTS user_role_type;

-- 1. Create Enum like MySQL ENUM
CREATE TYPE user_role_type AS ENUM ('customer', 'event_organizer', 'coordinator', 'venue_administrator', 'administrator');

-- 2. Trigger function to auto-update updated_at (Postgres replacement for ON UPDATE CURRENT_TIMESTAMP)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. Users table (uses INTEGER identity to match MySQL INT)
-- Linked to Supabase Auth via auth_id
CREATE TABLE users (
  user_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id         UUID UNIQUE NOT NULL,
  email           VARCHAR(255) NOT NULL UNIQUE,
  first_name      VARCHAR(100) NOT NULL,
  last_name       VARCHAR(100) NOT NULL,
  phone_number  VARCHAR(15) DEFAULT '',
  user_role       user_role_type NOT NULL DEFAULT 'customer',
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX index_user_role ON users (user_role);

-- trigger to keep updated_at in sync (emulates MySQL ON UPDATE CURRENT_TIMESTAMP)
CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Disable RLS so registration can insert
ALTER TABLE users DISABLE ROW LEVEL SECURITY;

-- 4. user_photos (user_id is primary key like your MySQL schema)
CREATE TABLE user_photos (
  user_id     INTEGER NOT NULL PRIMARY KEY,
  file_name   VARCHAR(255) NOT NULL,
  file_url    VARCHAR(500) NOT NULL,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_photos_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TRIGGER update_user_photos_updated_at
BEFORE UPDATE ON user_photos
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 5. event_organizers
CREATE TABLE event_organizers (
  organizer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER NOT NULL UNIQUE,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_event_organizers_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- 6. coordinators
CREATE TABLE coordinators (
  coordinator_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        INTEGER NOT NULL,
  organizer_id   INTEGER NOT NULL,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_coordinators_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_coordinators_organizer FOREIGN KEY (organizer_id) REFERENCES event_organizers(organizer_id) ON DELETE CASCADE
);

-- 7. venue_administrators
CREATE TABLE venue_administrators (
  venue_admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        INTEGER NOT NULL UNIQUE,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_venue_admins_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- 8. otp
CREATE TABLE otp (
  otp_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        INTEGER NOT NULL,
  otp_code_hash  CHAR(64) NOT NULL,
  otp_expiry     TIMESTAMP NOT NULL,
  otp_used_at    TIMESTAMP DEFAULT NULL,
  otp_attempts   INTEGER DEFAULT 0,
  last_otp_sent  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_user_otp UNIQUE (user_id, otp_code_hash),
  CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
CREATE INDEX index_otp_user_id ON otp (user_id);

-- 9. password_reset
CREATE TABLE password_reset (
  reset_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER NOT NULL,
  reset_token_hash CHAR(64) NOT NULL,
  expires_at      TIMESTAMP NOT NULL,
  used_at         TIMESTAMP DEFAULT NULL,
  last_token_sent TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
CREATE INDEX index_password_reset_expires_at ON password_reset (expires_at);
CREATE INDEX index_password_reset_user_id ON password_reset (user_id);

-- 10. email_verification
CREATE TABLE email_verification (
  verification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER NOT NULL,
  email_token_hash CHAR(64) NOT NULL,
  expires_at      TIMESTAMP NOT NULL,
  is_verified     BOOLEAN DEFAULT FALSE,
  verified_at     TIMESTAMP DEFAULT NULL,
  last_token_sent TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_email_verif_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
CREATE INDEX index_email_verification_user_id ON email_verification (user_id);

-- DISABLE Row Level Security on all tables (except users - it's disabled above)
ALTER TABLE user_photos DISABLE ROW LEVEL SECURITY;
ALTER TABLE event_organizers DISABLE ROW LEVEL SECURITY;
ALTER TABLE coordinators DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_administrators DISABLE ROW LEVEL SECURITY;
ALTER TABLE otp DISABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset DISABLE ROW LEVEL SECURITY;
ALTER TABLE email_verification DISABLE ROW LEVEL SECURITY;