-- 0. Create Enum types
CREATE TYPE user_role_type AS ENUM ('customer', 'event_organizer', 'coordinator', 'venue_administrator', 'administrator');
CREATE TYPE venue_contact_type AS ENUM ('Email', 'Phone');
CREATE TYPE door_type_enum AS ENUM ('Single', 'Double');
CREATE TYPE door_corner_enum AS ENUM ('Left', 'Right', 'Center');
CREATE TYPE door_swing_enum AS ENUM ('Inward', 'Outward');
CREATE TYPE door_hinge_enum AS ENUM ('Left', 'Right');
CREATE TYPE rate_type_enum AS ENUM ('Hourly', 'Daily');
CREATE TYPE seasonal_rate_type_enum AS ENUM ('Hourly', 'Daily', 'Package', 'All');
CREATE TYPE modifier_type_enum AS ENUM ('Fixed', 'Percentage');

-- 1. Trigger function to auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Users table
CREATE TABLE users (
  user_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id         UUID UNIQUE NOT NULL,
  email           VARCHAR(255) NOT NULL UNIQUE,
  first_name      VARCHAR(100) NOT NULL,
  last_name       VARCHAR(100) NOT NULL,
  phone_number    VARCHAR(20) DEFAULT NULL,
  user_role       user_role_type NOT NULL DEFAULT 'customer',
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_user_role ON users (user_role);

CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

ALTER TABLE users DISABLE ROW LEVEL SECURITY;

-- 3. User photos table
CREATE TABLE user_photos (
  user_id       INTEGER NOT NULL PRIMARY KEY,
  profile_photo VARCHAR(500) NOT NULL,
  file_name     VARCHAR(255) NOT NULL,
  file_url      VARCHAR(500) NOT NULL,
  is_primary    BOOLEAN NOT NULL DEFAULT FALSE,
  uploaded_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_photos_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TRIGGER update_user_photos_updated_at
BEFORE UPDATE ON user_photos
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 4. Customers table
CREATE TABLE customers (
  customer_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER NOT NULL UNIQUE,
  preferences   TEXT DEFAULT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_customers_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TRIGGER update_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 5. Event organizers table
CREATE TABLE event_organizers (
  organizer_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER NOT NULL UNIQUE,
  company_name    VARCHAR(150) NOT NULL,
  company_address VARCHAR(255) NOT NULL,
  business_email  VARCHAR(255) NOT NULL UNIQUE,
  business_number VARCHAR(20) NOT NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_event_organizers_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TRIGGER update_event_organizers_updated_at
BEFORE UPDATE ON event_organizers
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 6. Coordinators table
CREATE TABLE coordinators (
  coordinator_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           INTEGER NOT NULL UNIQUE,
  organizer_id      INTEGER NOT NULL,
  specialization    VARCHAR(100) NOT NULL,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_coordinators_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_coordinators_organizer FOREIGN KEY (organizer_id) REFERENCES event_organizers(organizer_id) ON DELETE CASCADE
);

CREATE TRIGGER update_coordinators_updated_at
BEFORE UPDATE ON coordinators
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 7. Venue administrators table
CREATE TABLE venue_administrators (
  venue_admin_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           INTEGER NOT NULL UNIQUE,
  assigned_venue_id INTEGER DEFAULT NULL,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_venue_admins_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_administrators_updated_at
BEFORE UPDATE ON venue_administrators
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 8. Administrators table
CREATE TABLE administrators (
  admin_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          INTEGER NOT NULL UNIQUE,
  position         VARCHAR(100) NOT NULL DEFAULT 'System Administrator',
  role_description TEXT NOT NULL,
  admin_notes      TEXT DEFAULT NULL,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_administrators_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TRIGGER update_administrators_updated_at
BEFORE UPDATE ON administrators
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 9. OTP table
CREATE TABLE otp (
  otp_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER NOT NULL,
  otp_code_hash CHAR(64) NOT NULL,
  otp_expiry    TIMESTAMP NOT NULL,
  otp_used_at   TIMESTAMP DEFAULT NULL,
  otp_attempts  INTEGER DEFAULT 0,
  last_otp_sent TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_user_otp UNIQUE (user_id, otp_code_hash),
  CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_otp_user_id ON otp (user_id);
CREATE INDEX idx_otp_expiry ON otp (otp_expiry);

-- 10. Password reset table
CREATE TABLE password_reset (
  reset_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER NOT NULL,
  reset_token_hash CHAR(64) NOT NULL,
  expires_at      TIMESTAMP NOT NULL,
  used_at         TIMESTAMP DEFAULT NULL,
  last_token_sent TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_password_reset_user_id ON password_reset (user_id);
CREATE INDEX idx_password_reset_expires_at ON password_reset (expires_at);

CREATE TRIGGER update_password_reset_updated_at
BEFORE UPDATE ON password_reset
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 11. Email verification table
CREATE TABLE email_verification (
  verification_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          INTEGER NOT NULL,
  email_token_hash CHAR(64) NOT NULL,
  expires_at       TIMESTAMP NOT NULL,
  is_verified      BOOLEAN DEFAULT FALSE,
  verified_at      TIMESTAMP DEFAULT NULL,
  last_token_sent  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_active_email_token UNIQUE (user_id, email_token_hash),
  CONSTRAINT fk_email_verif_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_email_verification_user_id ON email_verification (user_id);
CREATE INDEX idx_email_verification_expiry ON email_verification (expires_at);

CREATE TRIGGER update_email_verification_updated_at
BEFORE UPDATE ON email_verification
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 12. Event themes table
CREATE TABLE event_themes (
  event_theme_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  theme_name       VARCHAR(100) NOT NULL UNIQUE,
  theme_description TEXT NOT NULL,
  primary_color    VARCHAR(100) NOT NULL,
  secondary_color  VARCHAR(100) DEFAULT NULL,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_event_themes_updated_at
BEFORE UPDATE ON event_themes
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 13. Event categories table
CREATE TABLE event_categories (
  category_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(50) NOT NULL UNIQUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_event_categories_updated_at
BEFORE UPDATE ON event_categories
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 14. Decoration styles table
CREATE TABLE decoration_styles (
  decoration_style_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  style_name          VARCHAR(50) NOT NULL UNIQUE,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_decoration_styles_updated_at
BEFORE UPDATE ON decoration_styles
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 15. Lighting styles table
CREATE TABLE lighting_styles (
  lighting_style_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  style_name        VARCHAR(50) NOT NULL UNIQUE,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_lighting_styles_updated_at
BEFORE UPDATE ON lighting_styles
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 16. Event theme categories junction table
CREATE TABLE event_theme_categories (
  theme_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_theme_id    INTEGER NOT NULL,
  category_id       INTEGER NOT NULL,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_etc_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE CASCADE,
  CONSTRAINT fk_etc_category FOREIGN KEY (category_id) REFERENCES event_categories(category_id) ON DELETE CASCADE
);

CREATE TRIGGER update_event_theme_categories_updated_at
BEFORE UPDATE ON event_theme_categories
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 17. Event theme decorations junction table
CREATE TABLE event_theme_decorations (
  theme_decoration_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_theme_id       INTEGER NOT NULL,
  decoration_style_id  INTEGER NOT NULL,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_etd_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE CASCADE,
  CONSTRAINT fk_etd_decoration FOREIGN KEY (decoration_style_id) REFERENCES decoration_styles(decoration_style_id) ON DELETE CASCADE
);

CREATE TRIGGER update_event_theme_decorations_updated_at
BEFORE UPDATE ON event_theme_decorations
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 18. Event theme lighting junction table
CREATE TABLE event_theme_lighting (
  theme_lighting_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_theme_id     INTEGER NOT NULL,
  lighting_style_id  INTEGER NOT NULL,
  created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_etl_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE CASCADE,
  CONSTRAINT fk_etl_lighting FOREIGN KEY (lighting_style_id) REFERENCES lighting_styles(lighting_style_id) ON DELETE CASCADE
);

CREATE TRIGGER update_event_theme_lighting_updated_at
BEFORE UPDATE ON event_theme_lighting
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 19. Event theme accent colors table
CREATE TABLE event_theme_accent_colors (
  accent_color_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_theme_id  INTEGER NOT NULL,
  color_value     VARCHAR(100) NOT NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_etac_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE CASCADE
);

CREATE TRIGGER update_event_theme_accent_colors_updated_at
BEFORE UPDATE ON event_theme_accent_colors
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 20. Event theme images table
CREATE TABLE event_theme_images (
  image_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_theme_id INTEGER NOT NULL,
  image_path     VARCHAR(255) NOT NULL,
  is_thumbnail   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_eti_theme FOREIGN KEY (event_theme_id) REFERENCES event_themes(event_theme_id) ON DELETE CASCADE
);
CREATE INDEX idx_event_theme_id ON event_theme_images (event_theme_id);

CREATE TRIGGER update_event_theme_images_updated_at
BEFORE UPDATE ON event_theme_images
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 21. Venues table
CREATE TABLE venues (
  venue_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_name    VARCHAR(150) NOT NULL UNIQUE,
  description   TEXT NOT NULL,
  location      VARCHAR(255) NOT NULL,
  max_capacity  INTEGER NOT NULL,
  created_by    INTEGER NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_venues_creator FOREIGN KEY (created_by) REFERENCES users(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_venue_name ON venues (venue_name);

CREATE TRIGGER update_venues_updated_at
BEFORE UPDATE ON venues
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 22. Venue types table
CREATE TABLE venue_types (
  venue_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name     VARCHAR(100) NOT NULL UNIQUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_venue_types_updated_at
BEFORE UPDATE ON venue_types
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 23. Venue venue types junction table
CREATE TABLE venue_venue_types (
  venue_type_link_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id           INTEGER NOT NULL,
  venue_type_id      INTEGER NOT NULL,
  created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_venue_type UNIQUE (venue_id, venue_type_id),
  CONSTRAINT fk_vvt_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_vvt_type FOREIGN KEY (venue_type_id) REFERENCES venue_types(venue_type_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_venue_types_updated_at
BEFORE UPDATE ON venue_venue_types
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 24. Venue contacts table
CREATE TABLE venue_contacts (
  contact_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id      INTEGER NOT NULL,
  contact_type  venue_contact_type NOT NULL,
  contact_value VARCHAR(100) NOT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vc_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_contacts_updated_at
BEFORE UPDATE ON venue_contacts
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 25. Venue specifications table
CREATE TABLE venue_specifications (
  specification_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id            INTEGER NOT NULL,
  specification_name  VARCHAR(100) NOT NULL,
  specification_value VARCHAR(100) NOT NULL,
  notes               TEXT DEFAULT NULL,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_venue_spec UNIQUE (venue_id, specification_name),
  CONSTRAINT fk_vs_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_specifications_updated_at
BEFORE UPDATE ON venue_specifications
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 26. Venue allowed event types table
CREATE TABLE venue_allowed_event_types (
  venue_event_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id            INTEGER NOT NULL,
  category_id         INTEGER NOT NULL,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_venue_category UNIQUE (venue_id, category_id),
  CONSTRAINT fk_vaet_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_vaet_category FOREIGN KEY (category_id) REFERENCES event_categories(category_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_allowed_event_types_updated_at
BEFORE UPDATE ON venue_allowed_event_types
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 27. Venue images table
CREATE TABLE venue_images (
  image_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id     INTEGER NOT NULL,
  image_path   VARCHAR(255) NOT NULL,
  is_thumbnail BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vi_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);
CREATE INDEX idx_venue_id ON venue_images (venue_id);

CREATE TRIGGER update_venue_images_updated_at
BEFORE UPDATE ON venue_images
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 28. Venue facilities table
CREATE TABLE venue_facilities (
  facility_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id      INTEGER NOT NULL,
  facility_name VARCHAR(100) NOT NULL,
  description   TEXT DEFAULT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vf_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_facilities_updated_at
BEFORE UPDATE ON venue_facilities
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 29. Venue rules table
CREATE TABLE venue_rules (
  rule_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id    INTEGER NOT NULL,
  rule_text   TEXT NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vr_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_rules_updated_at
BEFORE UPDATE ON venue_rules
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 30. Venue floor plans table
CREATE TABLE venue_floor_plans (
  floor_plan_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id        INTEGER NOT NULL,
  floor_plan_file VARCHAR(255) NOT NULL,
  floor_plan_type VARCHAR(100) NOT NULL,
  description     TEXT DEFAULT NULL,
  length          DECIMAL(5, 2) NOT NULL,
  width           DECIMAL(5, 2) NOT NULL,
  height          DECIMAL(5, 2) NOT NULL,
  area_sqm        DECIMAL(7, 2) NOT NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vfp_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_floor_plans_updated_at
BEFORE UPDATE ON venue_floor_plans
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 31. Venue doors table
CREATE TABLE venue_doors (
  door_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id        INTEGER NOT NULL,
  door_type       door_type_enum NOT NULL,
  width           DECIMAL(5, 2) NOT NULL,
  height          DECIMAL(5, 2) NOT NULL,
  offset          DECIMAL(5, 2) NOT NULL,
  corner_position door_corner_enum NOT NULL DEFAULT 'Center',
  swing_direction door_swing_enum NOT NULL DEFAULT 'Inward',
  hinge_position  door_hinge_enum NOT NULL DEFAULT 'Left',
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vd_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_doors_updated_at
BEFORE UPDATE ON venue_doors
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 32. Venue base rates table
CREATE TABLE venue_base_rates (
  rate_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id       INTEGER NOT NULL,
  rate_type      rate_type_enum NOT NULL,
  base_price     DECIMAL(12, 2) NOT NULL,
  weekend_price  DECIMAL(12, 2) NOT NULL,
  holiday_price  DECIMAL(12, 2) NOT NULL,
  included_hours INTEGER NOT NULL,
  min_hours      INTEGER NOT NULL DEFAULT 2,
  notes          TEXT DEFAULT NULL,
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vbr_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_base_rates_updated_at
BEFORE UPDATE ON venue_base_rates
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 33. Venue overtime rates table
CREATE TABLE venue_overtime_rates (
  overtime_rate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id         INTEGER NOT NULL,
  rate_type        rate_type_enum NOT NULL,
  start_hour       INTEGER NOT NULL,
  end_hour         INTEGER DEFAULT NULL,
  price_per_hour   DECIMAL(12, 2) NOT NULL,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vor_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_overtime_rates_updated_at
BEFORE UPDATE ON venue_overtime_rates
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 34. Venue packages table
CREATE TABLE venue_packages (
  package_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id      INTEGER NOT NULL,
  package_name  VARCHAR(150) NOT NULL,
  description   TEXT NOT NULL,
  duration_hours INTEGER NOT NULL,
  duration_days INTEGER DEFAULT NULL,
  base_price    DECIMAL(12, 2) NOT NULL,
  min_hours     INTEGER NOT NULL,
  notes         TEXT DEFAULT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_package_name UNIQUE (venue_id, package_name),
  CONSTRAINT fk_vp_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);
CREATE INDEX idx_package_name ON venue_packages (package_name);

CREATE TRIGGER update_venue_packages_updated_at
BEFORE UPDATE ON venue_packages
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 35. Venue package inclusions table
CREATE TABLE venue_package_inclusions (
  inclusion_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id    INTEGER NOT NULL,
  inclusion_name VARCHAR(150) NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vpi_package FOREIGN KEY (package_id) REFERENCES venue_packages(package_id) ON DELETE CASCADE
);

CREATE TRIGGER update_venue_package_inclusions_updated_at
BEFORE UPDATE ON venue_package_inclusions
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 36. Venue seasonal pricing table
CREATE TABLE venue_seasonal_pricing (
  seasonal_price_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id          INTEGER NOT NULL,
  rate_type         seasonal_rate_type_enum NOT NULL,
  package_id        INTEGER DEFAULT NULL,
  season_name       VARCHAR(100) NOT NULL,
  start_date        DATE NOT NULL,
  end_date          DATE NOT NULL,
  modifier_type     modifier_type_enum NOT NULL,
  modifier_value    DECIMAL(10, 2) NOT NULL,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vsp_venue FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE,
  CONSTRAINT fk_vsp_package FOREIGN KEY (package_id) REFERENCES venue_packages(package_id) ON DELETE SET NULL
);
CREATE INDEX idx_season_name ON venue_seasonal_pricing (season_name);

CREATE TRIGGER update_venue_seasonal_pricing_updated_at
BEFORE UPDATE ON venue_seasonal_pricing
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();